In [2]:
import numpy as np

arraytosquare = np.arange(0, 100000)

%timeit arraytosquare**2

254 µs ± 14.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
print(arraytosquare)

[    0     1     2 ... 99997 99998 99999]


In [11]:
pythonlist = [1,2,3,4,5,6,7,8,9,10]
type(pythonlist)


list

In [12]:
a1 = np.array([pythonlist])
type(a1)


numpy.ndarray

In [13]:
numpy = np.arange(10)
numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
for val in pythonlist:
    print(val*2)

2
4
6
8
10
12
14
16
18
20


In [15]:
empty = []
for val in pythonlist:
    empty.append(val ** 2)
empty

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [16]:
numpy ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [17]:
numpy +5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
d2list = [[1,2,3],[4,5,6]]

In [19]:
d2list

[[1, 2, 3], [4, 5, 6]]

In [21]:
d2arr = np.array(d2list)
d2arr

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
d2array = np.arange(20).reshape(2,10)

In [28]:
d2array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [29]:
np.size(d2array)

20

In [32]:
np.array(range(10), dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
np.array(range(10), dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.size(d2array)

NameError: name 'm' is not defined